trying with a better (?) travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,29 +1,85 @@
-language: haskell
-ghc:
-  - '7.8'
-  - '7.10'
-sudo: false
+# This is thanks to https://github.com/thsutton/edit-distance-vector/blob/master/.travis.yml
 
-addons:
-  apt:
-    sources:
-      - hvr-ghc
-    packages:
-      - happy-1.19.4
-      - alex-3.1.3
-      - cabal-install-1.20
+# The following enables several GHC versions to be tested; often it's enough to
+# test only against the last release in a major GHC version. Feel free to omit
+# lines listings versions you don't need/want testing for.
+env:
+# - CABALVER=1.16 GHCVER=7.4.2
+# - CABALVER=1.18 GHCVER=7.6.3
+# - CABALVER=1.18 GHCVER=7.8.3
+# - CABALVER=1.22 GHCVER=7.10.1
+ - CABALVER=1.18 GHCVER=7.8.4
+ - CABALVER=1.22 GHCVER=7.10.2
 
 before_install:
-#  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
-#  - travis_retry sudo apt-get update
-#  - travis_retry sudo apt-get install --force-yes happy-1.19.4 alex-3.1.3 cabal-install-1.20
-  - export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:/opt/cabal/1.20/bin:$PATH
-  - cabal update
-  - cabal install Cabal
+ # If $GHCVER is the one travis has, don't bother reinstalling it.
+ # We can also have faster builds by installing some libraries with
+ # `apt`. If it isn't, install the GHC we want from hvr's PPA along
+ # with cabal-1.18.
+ - |
+   if [ $GHCVER = `ghc --numeric-version` ]; then
+     travis/cabal-apt-install --enable-tests $MODE
+     export CABAL=cabal
+   else
+     travis_retry sudo add-apt-repository -y ppa:hvr/ghc
+     travis_retry sudo apt-get update
+     travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
+     export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
+   fi
 
 install:
-  - cabal install --only-dependencies --enable-tests --reorder-goals
+ - cabal --version
+ - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
+ - travis_retry cabal update
+ - cabal install --only-dependencies --enable-tests --enable-benchmarks
 
+# Here starts the actual work to be performed for the package under test; any
+# command which exits with a non-zero exit code causes the build to fail.
 script:
-  - cabal configure --enable-tests && cabal build && cabal test
+ - cabal configure --enable-tests --enable-benchmarks -v2
+ - cabal build
+ - cabal test
+ - cabal check
+ - cabal sdist
+ - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
+   cd dist/;
+   if [ -f "$SRC_TGZ" ]; then
+      cabal install --force-reinstalls "$SRC_TGZ";
+   else
+      echo "expected '$SRC_TGZ' not found";
+      exit 1;
+   fi
 
+
+
+### OLD
+
+#language: haskell
+#ghc:
+#  - '7.8'
+##  - '7.10'
+#sudo: false
+#
+#addons:
+#  apt:
+#    sources:
+#      - hvr-ghc
+#    packages:
+#      - happy-1.19.4
+#      - alex-3.1.3
+#      - cabal-install-1.20
+#
+#before_install:
+##  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
+##  - travis_retry sudo apt-get update
+##  - travis_retry sudo apt-get install --force-yes happy-1.19.4 alex-3.1.3 cabal-install-1.20
+#  - export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:/opt/cabal/1.20/bin:$PATH
+#  - ls /opt/cabal/*
+#  - cabal update
+##  - cabal install Cabal
+#
+#install:
+#  - cabal install --only-dependencies --enable-tests --reorder-goals
+#
+#script:
+#  - cabal configure --enable-tests && cabal build && cabal test
